#' Prepare National-scale Effort Data For MEMOIR.fit input
#'  
#' Takes data from a national-scale mark-recapture
#' database and formats it for input to MEMOIR.fit. Inputs are vectors from a table
#' equivalent to outputEffort (length P), which would be generated by MEMOIR.sim
#' for simulated populations.
#' @param YEAR Numeric or date vector specifying the year in which animals were banded
#' @param SPECIES Text factor specifying the scientific name of the species
#' @param LOC Text factor specifying the location at which animals were banded
#' @param BANDED Integer. The number of animals banded in that year at that location
#' @return The function returns a table formatted in the same way as MEMOIR.sim[[2]]
#'         c("recRepNo", "BAND", "SCIENA", "BANDED", "RECOVERED", "ELAPSED_DAYS", "BANDYEAR",
#'           "BANDLOC", "RECOVERYEAR"), for input to MEMOIR.fit as 'records'
#' @export
#' @examples
#' with(effort, effort.fitfeeder(YEAR, SPECIES, LOC, BANDED, splitBy))

effort.fitfeeder <- function(YEAR, SPECIES, LOC, BANDED, splitBy) {

    YEAR <- YEAR  ## will output as numeric, is converted to date in MEMOIR.fit
    SPECIES <- SPECIES
    CAVS <- floor(runif(length(YEAR), 100, 500))
    LOC <- LOC
    BANDED <- as.integer(BANDED)
    eRepNo <- as.numeric(splitBy)

    effort <- data.frame(eRepNo, YEAR, CAVS, SPECIES, LOC, BANDED)
    return(effort)
}
