#' MEMOIR.rmse(): calculate root mean squared error of a series of survival estimates
#'                generated by MEMOIR.simplotter() at a set of given sampling ages with
#'                a set of given true values.
#'
#' Returns the Root Mean Squared Error of the estimate at the given sampling ages. Output is
#' formatted as a dataframe, with ages as column one, proportional survival as column two,
#' and RMSE as column three.
#'
#' @param estimates A dataframe of fitted model predictions from MEMOIR.simplotter(). Must
#'                  have names as c("iter", "ages", "numberAlive", "propAlive"), where
#'                  iter is iteration number, ages are ages (in days), numberAlive is the
#'                  fitted-model number of animals alive, and propAlive is the fitted-model
#'                  proportion of animals alive.
#' @param ages A vector of ages (in years) at which to estimate the root mean squared error
#'             of the estimate. Defaults to c(5,10,15).
#' @param proportions A vector of (true) proportional survival at the ages given in ages.
#'                    Defaults to c(0.75, 0.5, 0.25), which are the survival rates for
#'                    Curve A (Baylis, PhD thesis) at 5, 10, and 15 years of age.
#' @export



MEMOIR.rmse <- function(estimates, ages = c(5,10,15), proportions = c(0.75, 0.5, 0.25)) {
    pointsByIters <- matrix(data = NaN, nrow = length(unique(estimates$iter)),
                            ncol = length(ages))
    for (i in 1:nrow(pointsByIters)) {
        activeIter <- subset(estimates, estimates$iter == unique(estimates$iter)[i])
        xErrors <- matrix(data = NaN, nrow = 1, ncol = length(ages))
        for (j in 1:ncol(xErrors)) {
            samplePoint <- activeIter[abs(activeIter$ages - ages[j]*365)
                                      == min(abs(activeIter$ages - ages[j]*365)),]
            xErrors[,j] <- abs(samplePoint$propAlive[1] - proportions[j])
        }
        pointsByIters[i,] <- xErrors
    }
    squaredErrors <- pointsByIters^2
    meanSquaredErrors <- matrix(data = NaN, nrow = 1, ncol = ncol(squaredErrors))
    for (k in 1:ncol(meanSquaredErrors) ) {
        meanSquaredErrors[,k] <- mean(squaredErrors[,k])
    }
    RMSE <- sqrt(meanSquaredErrors)
    RMSE <- data.frame(ages = ages, propSurv = proportions, RMSE = as.vector(RMSE[1,]))
    return(RMSE)
}
