#' Prepare National-Scale Records Data For MEMOIR.fit Input
#'
#' Takes data from a national-scale mark-recapture
#' database and formats it for input to MEMOIR.fit. Inputs are vectors from a table
#' equivalent to outputRecords (length N), which would be generated by MEMOIR.sim
#' for simulated populations.
#' @param BAND Numeric or text vector of length N. Unique codes identifying each individual.
#' @param SCIENA Text vector of length N. Binomial scientific name identifying the individual's
#'               species.
#' @param BANDED Date vector of length N, formatted as YYYY-mm-dd. The date the animal was
#'               banded.
#' @param RECOVERED Date vector of length N, formatted as YYYY-mm-dd. The date the animal
#'                  was (last) recovered or observed. 
#' @param BANDLOC Text or numeric vector of length N. Unique values for each marking location
#'                (i.e., Australian 'locode', or equivalent). Values must be coded the same
#'                way as in effort.fitfeeder for input to MEMOIR.fit.
#' @param SplitBy One of c("BANDLOC", "SCIENA"). Indicates which groups will be used for
#'                separate models in MEMOIR-fit. "SCIENA" gives separate curves for each
#'                species, and "BANDLOC" give separate curves for each location.
#' @return The function returns a table formatted in the same way as MEMOIR.sim[[1]]
#'         c("recRepNo", "BAND", "SCIENA", "BANDED", "RECOVERED", "ELAPSED_DAYS", "BANDYEAR",
#'           "BANDLOC", "RECOVERYEAR"), for input to MEMOIR.fit as 'records'.
#' @export
#' @examples
#' with(records, records.fitfeeder(BAND=bandNo, SCIENA=sciName, BANDED=bandDate,
#'      RECOVERED=recoverDate, BANDLOC=locode)) 

records.fitfeeder <- function(BAND, SCIENA, BANDED, RECOVERED, BANDLOC, SplitBy=c("SCIENA")) {
   recRepNo <- as.numeric(SplitBy)
   BANDED <- as.Date(BANDED, format="%Y-%m-%d")
   RECOVERED <- as.Date(RECOVERED, format="%Y-%m-%d")
   ELAPSED_DAYS <- as.numeric(RECOVERED-BANDED)
   BANDYEAR <- format(BANDED, "%Y")
   RECOVERYEAR <- format(RECOVERED, "%Y")
   if(SplitBy=="SCIENA") {
      recRepNo <- as.numeric(SCIENA)
   } else if(SplitBy=="BANDLOC") {
      recRepNo <- as.numeric(BANDLOC)
   } else if(SplitBy %in% c("BANDLOC", "SCIENA") == FALSE) {
      print("Your SplitBy choice isn't one of the options!")
   }
   records <- data.frame(BAND, SCIENA, BANDED, RECOVERED, ELAPSED_DAYS, BANDYEAR, BANDLOC, RECOVERYEAR)
   records <- subset(records, ELAPSED_DAYS >= 0) ## data-cleaning: will remove animals recovered before
                                                  # they were banded
   return(records)
}
